# Generated by Django 5.2.9 on 2025-12-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measurement', models.CharField(choices=[('pkts', 'Pkts'), ('pcs', 'Pcs'), ('bundles', 'Bundles'), ('dozen', 'Dozen'), ('pairs', 'Pairs'), ('rolls', 'Rolls')], max_length=50)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('job_roles', models.CharField(choices=[('project manager', 'Project Manager'), ('quality control', 'Quality Control'), ('project engineer', 'Project Engineer'), ('RA manger', 'RA Manager'), ('box Keeper', 'Box Keeper'), ('planner', 'Planner'), ('site_admin', 'Site Admin'), ('logistics', 'Logistics'), ('store-keeper', 'Store-Keeper'), ('purchasing officer', 'Purchasing Officer'), ('transport officer', 'Transport Officer'), ('hse coordinator', 'HSE Coordinator'), ('supervisor', 'Supervisor'), ('team lead', 'Team Lead'), ('box keeper', 'Box Keeper'), ('worker', 'Worker')], max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='store.department')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='store.items')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='store.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='stock_document')),
                ('comment', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='store.items')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
