# Generated by Django 5.2.9 on 2025-12-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_items_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='qty',
            new_name='quantity',
        ),
    ]
