# Generated by Django 5.2.9 on 2025-12-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_qty_stockin_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='quantity',
        ),
        migrations.CreateModel(
            name='IssuanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.issuance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='store.item')),
            ],
        ),
    ]
