# Generated by Django 5.2.9 on 2026-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_issuance_item_remove_issuance_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True),
        ),
    ]
