# Generated by Django 5.2.9 on 2026-01-03 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_item_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='issuance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issuance',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuance',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuance',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_issuances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.staff'),
        ),
    ]
