# Generated by Django 5.2.9 on 2026-01-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_item_item_description_issuance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='is_reversed',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='reversed_at',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='reversed_by',
        ),
    ]
