# Generated by Django 5.2.9 on 2026-01-06 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_issuance_is_reversed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='store.staff'),
        ),
        migrations.CreateModel(
            name='IssuanceReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal', to='store.issuance')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issuance Reversal',
                'verbose_name_plural': 'Issuance Reversals',
            },
        ),
    ]
