# Generated by Django 5.2.9 on 2026-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_issuance_created_at_alter_issuance_issued_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
