# Generated by Django 5.2.9 on 2026-01-10 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_issuance_is_reversed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_issuances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='store.staff'),
        ),
    ]
