# Generated by Django 5.2.9 on 2026-01-11 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_issuance_reversal_reason_issuance_reversed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='is_reversed',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='reversal_reason',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='reversed_at',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='reversed_by',
        ),
        migrations.CreateModel(
            name='IssuanceReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='store.issuance')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_issuances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
