# Generated by Django 5.2.9 on 2026-01-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_issuance_is_reversed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuancereversal',
            name='is_reversed',
        ),
        migrations.AddField(
            model_name='issuance',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
