# Generated by Django 5.2.9 on 2026-01-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.item')),
                ('stockin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.stockin')),
            ],
        ),
    ]
