# Generated by Django 5.2.9 on 2026-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_stockin_item_remove_stockin_quantity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockinitem',
            constraint=models.UniqueConstraint(fields=('stockin', 'item'), name='unique_item_per_stockin'),
        ),
        migrations.AddConstraint(
            model_name='stockinitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stockinitem_quantity_gt_zero'),
        ),
    ]
