# Generated by Django 5.2.9 on 2026-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_stockinitem_unique_item_per_stockin_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issuanceitem',
            constraint=models.UniqueConstraint(fields=('issuance', 'item'), name='unique_item_per_issuance'),
        ),
        migrations.AddConstraint(
            model_name='issuanceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='issuanceitem_quantity_gt_zero'),
        ),
    ]
