# Generated by Django 5.2.9 on 2026-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_issuanceitem_unique_item_per_issuance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
