# Generated by Django 5.2.9 on 2026-01-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuanceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_items', to='store.item'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_roles',
            field=models.CharField(choices=[('project manager', 'Project Manager'), ('quality control', 'Quality Control'), ('project engineer', 'Project Engineer'), ('RA manager', 'RA Manager'), ('box keeper', 'Box Keeper'), ('planner', 'Planner'), ('site_admin', 'Site Admin'), ('logistics', 'Logistics'), ('store-keeper', 'Store-Keeper'), ('purchasing officer', 'Purchasing Officer'), ('transport officer', 'Transport Officer'), ('hse coordinator', 'HSE Coordinator'), ('supervisor', 'Supervisor'), ('team lead', 'Team Lead'), ('worker', 'Worker')], max_length=50),
        ),
    ]
