# Generated by Django 5.2.9 on 2026-01-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_issuance_reversed_at_issuance_reversed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('STOCKIN_CREATED', 'Stock-in created'), ('ISSUANCE_CREATED', 'Issuance created'), ('ISSUANCE_REVERSED', 'Issuance reversed'), ('ISSUANCE_FAILED', 'Issuance failed'), ('LOW_STOCK_ALERT', 'Low stock alert')], max_length=50)),
                ('target_type', models.CharField(help_text='Model name, e.g. Issuance, StockIn, Item', max_length=50)),
                ('target_id', models.PositiveIntegerField(help_text='Primary key of the affected object')),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verb'], name='store_activ_verb_0df9aa_idx'), models.Index(fields=['target_type', 'target_id'], name='store_activ_target__5bc832_idx'), models.Index(fields=['created_at'], name='store_activ_created_f01353_idx')],
            },
        ),
    ]
