# Generated by Django 5.2.9 on 2026-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='target_type',
            field=models.CharField(help_text='Model name e.g. Issuance, StockIn, Item', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='stock_document/'),
        ),
    ]
