# Generated by Django 5.2.9 on 2026-03-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_activity_target_type_alter_stockin_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('staff_edited', 'Staff edited'), ('store_edited', 'Store edited'), ('submitted', 'Submitted'), ('fulfilled', 'Fulfilled'), ('fulfillment_edited', 'Fulfillment edited'), ('locked', 'Locked')], db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.PositiveIntegerField()),
                ('fulfilled_qty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='issuance',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_type',
            field=models.CharField(help_text='Model name e.g. Issuance, StockIn, Item, Request', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('STOCKIN_CREATED', 'Stock-in created'), ('ISSUANCE_CREATED', 'Issuance created'), ('ISSUANCE_UPDATED', 'Issuance updated'), ('ISSUANCE_REVERSED', 'Issuance reversed'), ('ISSUANCE_FAILED', 'Issuance failed'), ('LOW_STOCK_ALERT', 'Low stock alert'), ('REQUEST_CREATED', 'Request created'), ('REQUEST_UPDATED', 'Request updated'), ('REQUEST_SUBMITTED', 'Request submitted'), ('REQUEST_FULFILLED', 'Request fulfilled')], max_length=50),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('fulfilled', 'Fulfilled'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('store_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('editable_until', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_requests', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='store.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issuance',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='store.request'),
        ),
        migrations.AddIndex(
            model_name='issuance',
            index=models.Index(fields=['issued_at'], name='store_issua_issued__c48877_idx'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='store.request'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='store.item'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.request'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='store_reque_status_455bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_at'], name='store_reque_created_839934_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['submitted_at'], name='store_reque_submitt_81334a_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['fulfilled_at'], name='store_reque_fulfill_e046e2_idx'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['action'], name='store_reque_action_c5423e_idx'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['created_at'], name='store_reque_created_4d4202_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.UniqueConstraint(fields=('request', 'item'), name='unique_item_per_request'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0)), name='requestitem_requested_qty_gt_zero'),
        ),
    ]
