# Generated by Django 5.2.4 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_requestactivity_requestitem_alter_issuance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="needs_resubmission",
            field=models.BooleanField(default=False),
        ),
    ]
