# Generated by Django 5.2.9 on 2026-05-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_requestitem_original_requested_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_requests', 'Can approve store requests')]},
        ),
        migrations.AddField(
            model_name='request',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='approved_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('STOCKIN_CREATED', 'Stock-in created'), ('ISSUANCE_CREATED', 'Issuance created'), ('ISSUANCE_UPDATED', 'Issuance updated'), ('ISSUANCE_REVERSED', 'Issuance reversed'), ('ISSUANCE_FAILED', 'Issuance failed'), ('LOW_STOCK_ALERT', 'Low stock alert'), ('REQUEST_CREATED', 'Request created'), ('REQUEST_UPDATED', 'Request updated'), ('REQUEST_SUBMITTED', 'Request submitted'), ('REQUEST_FULFILLED', 'Request fulfilled'), ('REQUEST_PENDING', 'Request pending approval'), ('REQUEST_APPROVED', 'Request approved'), ('REQUEST_REJECTED', 'Request rejected'), ('REQUEST_ESCALATED', 'Request escalated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('fulfilled', 'Fulfilled'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('staff_edited', 'Staff edited'), ('store_edited', 'Store edited'), ('submitted', 'Submitted'), ('fulfilled', 'Fulfilled'), ('fulfillment_edited', 'Fulfillment edited'), ('locked', 'Locked'), ('supervisor_edited', 'Supervisor edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('pending', 'Pending')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_supervisor', models.BooleanField(default=False)),
                ('supervisor_since', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('stockin_created', 'Stock-in created'), ('issuance_created', 'Issuance created'), ('issuance_updated', 'Issuance updated'), ('issuance_reversed', 'Issuance reversed'), ('issuance_failed', 'Issuance failed'), ('low_stock_alert', 'Low stock alert'), ('request_created', 'Request created'), ('request_updated', 'Request updated'), ('REQUEST_SUBMITTED', 'Request submitted'), ('REQUEST_FULFILLED', 'Request fulfilled'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('request_escalated', 'Request escalated'), ('request_pending', 'Request pending approval')], db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='store_notif_recipie_7960ef_idx'), models.Index(fields=['created_at'], name='store_notif_created_441975_idx')],
            },
        ),
    ]
