# Generated by Django 5.2.9 on 2026-05-17 10:37

from django.db import migrations


def migrate_submitted_to_pending(apps, schema_editor):
    Request = apps.get_model("store", "Request")
    Request.objects.filter(status="submitted").update(status="pending")


def reverse_pending_to_submitted(apps, schema_editor):
    Request = apps.get_model("store", "Request")
    Request.objects.filter(status="pending").update(status="submitted")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_add_supervisor_approval_layer'),
    ]

    operations = [
        migrations.RunPython(
            migrate_submitted_to_pending,
            reverse_pending_to_submitted,
        ),
    ]
